name: triggers #Nombre del workflow
run-name: triggers workflow
on: [push, issues, issue_comment, workflow_dispatch] #evento que lo activar치
jobs: #Definici칩n de los jobs
  triggers: #Nombre del job
    env:
      VAR_1: ${{vars.VAR_1}}
      VAR_2: "Mi variable 2, est치tica"
    runs-on: ubuntu-latest #Maquina en la que correr치
    steps: #Lista de steps del job hola-mundo
      - name: event name
        run: "echo ${{toJSON(github.event_name)}}"

      - name: var1
        run: echo $VAR_1

      - name: print env
        run: echo "${{env}}"

      - name: "print github:"
        run: echo "${{toJSON(github)}}"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies with pnpm
        run: pnpm install

      - name: Run index
        run: node index.js
      - run: date
